# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ld21ERhU-khuuWSWZ6YgeTlUyeQ1PX0Q
"""

import numpy as np
import pandas as pd
import sys
import os
import time
import random
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

def pie_plot(labels,sizes,img_name):
    plt.figure(figsize = (9,6),facecolor=(1, 1, 1))
    plt.pie(sizes, autopct='%1.1f%%',labels=labels,pctdistance=0.7, startangle = 270, labeldistance=1.1,shadow = True,textprops={'fontsize': 14})
    plt.axis('equal') 
    plt.show()
    #plt.savefig("/Users/css2211/Projects/fall2022-project1-Chaitanya1011/figs/" + img_name)

